name: practice_today
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  firebase_core: ^2.17.0
  google_fonts: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/apple.svg
    - assets/images/icons/google.svg
    - assets/images/icons/facebook.svg
    - assets/images/icons/email.svg
    - assets/images/icons/Jiggy.png
    - assets/images/icons/Frame.png
    - assets/images/icons/mainlogo.png
    - assets/images/icons/Vector (1).png 
    - assets/images/icons/Vector.png
    - assets/images/icons/Group.png
